name: iOS Pull Request

on:
  pull_request:
    types: [ opened, reopened, synchronize, ready_for_review ]
    branches: [ main ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build and Test default scheme using any available iPhone simulator
    if: github.event.pull_request.draft == false
    runs-on: macos-26

    steps:
      - name: Add path globally
        run: echo "/usr/local/bin" >> $GITHUB_PATH

      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # pin@v4
        with:
          lfs: 'true'
          fetch-depth: 0

      - name: Run Linter
        run: |
          brew install swiftlint
          swiftlint --strict

      - name: Validate Pull Request Name
        id: versioning
        uses: Oliver-Binns/Versioning@be1807ff3c5cd06edbe8fa3de54076cfd505f2df # pin@v1.4.3
        with:
          ACTION_TYPE: 'Validate'

      - name: Xcode select
        run: |
          sudo xcode-select -s /Applications/Xcode_26.2.app
          
      - name: Build and Test
        run: |
          set -o pipefail && xcodebuild -scheme Authentication test \
            -destination "platform=iOS Simulator,name=iPhone 17,OS=26.2" \
            -enableCodeCoverage YES \
            -resultBundlePath result.xcresult | xcbeautify
          
      - name: Run SonarCloud Scanning
        run: |
          bash xccov-to-sonarqube-generic.sh result.xcresult > sonarqube-generic-coverage.xml
          
          brew install sonar-scanner

          pull_number=$(jq --raw-output .pull_request.number "$GITHUB_EVENT_PATH")

          sonar-scanner \
            -Dsonar.token=$SONAR_TOKEN \
            -Dsonar.coverageReportPaths="sonarqube-generic-coverage.xml" \
            -Dsonar.pullrequest.key=$pull_number \
            -Dsonar.pullrequest.branch=${{github.head_ref}} \
            -Dsonar.pullrequest.base=${{github.base_ref}}
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Check SonarCloud Results
        uses: sonarsource/sonarqube-quality-gate-action@cf038b0e0cdecfa9e56c198bbb7d21d751d62c3b # pin@v1.2.0
        # Force to fail step after specific time
        timeout-minutes: 5
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
